# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from dji_osdk_ros/iuslTarState.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class iuslTarState(genpy.Message):
  _md5sum = "d0db4d134f168ed502ff7b4539d66987"
  _type = "dji_osdk_ros/iuslTarState"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """# estimated target UAV state

float64 time

bool tar_OK
bool is_laser_measured

float64 tar_x
float64 tar_y
float64 tar_z
float64 tar_vx
float64 tar_vy

float64 fuse_dis

"""
  __slots__ = ['time','tar_OK','is_laser_measured','tar_x','tar_y','tar_z','tar_vx','tar_vy','fuse_dis']
  _slot_types = ['float64','bool','bool','float64','float64','float64','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       time,tar_OK,is_laser_measured,tar_x,tar_y,tar_z,tar_vx,tar_vy,fuse_dis

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(iuslTarState, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.time is None:
        self.time = 0.
      if self.tar_OK is None:
        self.tar_OK = False
      if self.is_laser_measured is None:
        self.is_laser_measured = False
      if self.tar_x is None:
        self.tar_x = 0.
      if self.tar_y is None:
        self.tar_y = 0.
      if self.tar_z is None:
        self.tar_z = 0.
      if self.tar_vx is None:
        self.tar_vx = 0.
      if self.tar_vy is None:
        self.tar_vy = 0.
      if self.fuse_dis is None:
        self.fuse_dis = 0.
    else:
      self.time = 0.
      self.tar_OK = False
      self.is_laser_measured = False
      self.tar_x = 0.
      self.tar_y = 0.
      self.tar_z = 0.
      self.tar_vx = 0.
      self.tar_vy = 0.
      self.fuse_dis = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_d2B6d().pack(_x.time, _x.tar_OK, _x.is_laser_measured, _x.tar_x, _x.tar_y, _x.tar_z, _x.tar_vx, _x.tar_vy, _x.fuse_dis))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 58
      (_x.time, _x.tar_OK, _x.is_laser_measured, _x.tar_x, _x.tar_y, _x.tar_z, _x.tar_vx, _x.tar_vy, _x.fuse_dis,) = _get_struct_d2B6d().unpack(str[start:end])
      self.tar_OK = bool(self.tar_OK)
      self.is_laser_measured = bool(self.is_laser_measured)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_d2B6d().pack(_x.time, _x.tar_OK, _x.is_laser_measured, _x.tar_x, _x.tar_y, _x.tar_z, _x.tar_vx, _x.tar_vy, _x.fuse_dis))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 58
      (_x.time, _x.tar_OK, _x.is_laser_measured, _x.tar_x, _x.tar_y, _x.tar_z, _x.tar_vx, _x.tar_vy, _x.fuse_dis,) = _get_struct_d2B6d().unpack(str[start:end])
      self.tar_OK = bool(self.tar_OK)
      self.is_laser_measured = bool(self.is_laser_measured)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_d2B6d = None
def _get_struct_d2B6d():
    global _struct_d2B6d
    if _struct_d2B6d is None:
        _struct_d2B6d = struct.Struct("<d2B6d")
    return _struct_d2B6d
