# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from dji_osdk_ros/iuslMyState.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class iuslMyState(genpy.Message):
  _md5sum = "acb74560be271ca4b46ca1a39952dd6b"
  _type = "dji_osdk_ros/iuslMyState"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """float64 UAV_lat
float64 UAV_lon
float64 UAV_alt
float64 UAV_yaw
float64 UAV_vx
float64 UAV_vy
float64 cam_x
float64 cam_y
float64 cam_z

"""
  __slots__ = ['UAV_lat','UAV_lon','UAV_alt','UAV_yaw','UAV_vx','UAV_vy','cam_x','cam_y','cam_z']
  _slot_types = ['float64','float64','float64','float64','float64','float64','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       UAV_lat,UAV_lon,UAV_alt,UAV_yaw,UAV_vx,UAV_vy,cam_x,cam_y,cam_z

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(iuslMyState, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.UAV_lat is None:
        self.UAV_lat = 0.
      if self.UAV_lon is None:
        self.UAV_lon = 0.
      if self.UAV_alt is None:
        self.UAV_alt = 0.
      if self.UAV_yaw is None:
        self.UAV_yaw = 0.
      if self.UAV_vx is None:
        self.UAV_vx = 0.
      if self.UAV_vy is None:
        self.UAV_vy = 0.
      if self.cam_x is None:
        self.cam_x = 0.
      if self.cam_y is None:
        self.cam_y = 0.
      if self.cam_z is None:
        self.cam_z = 0.
    else:
      self.UAV_lat = 0.
      self.UAV_lon = 0.
      self.UAV_alt = 0.
      self.UAV_yaw = 0.
      self.UAV_vx = 0.
      self.UAV_vy = 0.
      self.cam_x = 0.
      self.cam_y = 0.
      self.cam_z = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_9d().pack(_x.UAV_lat, _x.UAV_lon, _x.UAV_alt, _x.UAV_yaw, _x.UAV_vx, _x.UAV_vy, _x.cam_x, _x.cam_y, _x.cam_z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 72
      (_x.UAV_lat, _x.UAV_lon, _x.UAV_alt, _x.UAV_yaw, _x.UAV_vx, _x.UAV_vy, _x.cam_x, _x.cam_y, _x.cam_z,) = _get_struct_9d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_9d().pack(_x.UAV_lat, _x.UAV_lon, _x.UAV_alt, _x.UAV_yaw, _x.UAV_vx, _x.UAV_vy, _x.cam_x, _x.cam_y, _x.cam_z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 72
      (_x.UAV_lat, _x.UAV_lon, _x.UAV_alt, _x.UAV_yaw, _x.UAV_vx, _x.UAV_vy, _x.cam_x, _x.cam_y, _x.cam_z,) = _get_struct_9d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_9d = None
def _get_struct_9d():
    global _struct_9d
    if _struct_9d is None:
        _struct_9d = struct.Struct("<9d")
    return _struct_9d
