# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from dji_osdk_ros/iuslDetectionResult.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class iuslDetectionResult(genpy.Message):
  _md5sum = "8e3ffe678e32878975c83b6d54d3b961"
  _type = "dji_osdk_ros/iuslDetectionResult"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """# boundingbox
int64 center_x
int64 center_y
int64 max_length

# gimbal state
float64 pitch
float64 yaw
float64 roll

# UAV state
float64 UAV_lat
float64 UAV_lon
float64 UAV_alt
float64 UAV_vx
float64 UAV_vy

# laser state
float64 laser_dis

"""
  __slots__ = ['center_x','center_y','max_length','pitch','yaw','roll','UAV_lat','UAV_lon','UAV_alt','UAV_vx','UAV_vy','laser_dis']
  _slot_types = ['int64','int64','int64','float64','float64','float64','float64','float64','float64','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       center_x,center_y,max_length,pitch,yaw,roll,UAV_lat,UAV_lon,UAV_alt,UAV_vx,UAV_vy,laser_dis

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(iuslDetectionResult, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.center_x is None:
        self.center_x = 0
      if self.center_y is None:
        self.center_y = 0
      if self.max_length is None:
        self.max_length = 0
      if self.pitch is None:
        self.pitch = 0.
      if self.yaw is None:
        self.yaw = 0.
      if self.roll is None:
        self.roll = 0.
      if self.UAV_lat is None:
        self.UAV_lat = 0.
      if self.UAV_lon is None:
        self.UAV_lon = 0.
      if self.UAV_alt is None:
        self.UAV_alt = 0.
      if self.UAV_vx is None:
        self.UAV_vx = 0.
      if self.UAV_vy is None:
        self.UAV_vy = 0.
      if self.laser_dis is None:
        self.laser_dis = 0.
    else:
      self.center_x = 0
      self.center_y = 0
      self.max_length = 0
      self.pitch = 0.
      self.yaw = 0.
      self.roll = 0.
      self.UAV_lat = 0.
      self.UAV_lon = 0.
      self.UAV_alt = 0.
      self.UAV_vx = 0.
      self.UAV_vy = 0.
      self.laser_dis = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3q9d().pack(_x.center_x, _x.center_y, _x.max_length, _x.pitch, _x.yaw, _x.roll, _x.UAV_lat, _x.UAV_lon, _x.UAV_alt, _x.UAV_vx, _x.UAV_vy, _x.laser_dis))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 96
      (_x.center_x, _x.center_y, _x.max_length, _x.pitch, _x.yaw, _x.roll, _x.UAV_lat, _x.UAV_lon, _x.UAV_alt, _x.UAV_vx, _x.UAV_vy, _x.laser_dis,) = _get_struct_3q9d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3q9d().pack(_x.center_x, _x.center_y, _x.max_length, _x.pitch, _x.yaw, _x.roll, _x.UAV_lat, _x.UAV_lon, _x.UAV_alt, _x.UAV_vx, _x.UAV_vy, _x.laser_dis))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 96
      (_x.center_x, _x.center_y, _x.max_length, _x.pitch, _x.yaw, _x.roll, _x.UAV_lat, _x.UAV_lon, _x.UAV_alt, _x.UAV_vx, _x.UAV_vy, _x.laser_dis,) = _get_struct_3q9d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3q9d = None
def _get_struct_3q9d():
    global _struct_3q9d
    if _struct_3q9d is None:
        _struct_3q9d = struct.Struct("<3q9d")
    return _struct_3q9d
