# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from dji_osdk_ros/iuslGimbalCmd.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class iuslGimbalCmd(genpy.Message):
  _md5sum = "60c32efa40c7049d37a43f7259ece1c9"
  _type = "dji_osdk_ros/iuslGimbalCmd"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """int8 mode    # 0,global fram;   1,local fram
float64 pitch
float64 roll
float64 yaw
float64 time  # seconds
"""
  __slots__ = ['mode','pitch','roll','yaw','time']
  _slot_types = ['int8','float64','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       mode,pitch,roll,yaw,time

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(iuslGimbalCmd, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.mode is None:
        self.mode = 0
      if self.pitch is None:
        self.pitch = 0.
      if self.roll is None:
        self.roll = 0.
      if self.yaw is None:
        self.yaw = 0.
      if self.time is None:
        self.time = 0.
    else:
      self.mode = 0
      self.pitch = 0.
      self.roll = 0.
      self.yaw = 0.
      self.time = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_b4d().pack(_x.mode, _x.pitch, _x.roll, _x.yaw, _x.time))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 33
      (_x.mode, _x.pitch, _x.roll, _x.yaw, _x.time,) = _get_struct_b4d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_b4d().pack(_x.mode, _x.pitch, _x.roll, _x.yaw, _x.time))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 33
      (_x.mode, _x.pitch, _x.roll, _x.yaw, _x.time,) = _get_struct_b4d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_b4d = None
def _get_struct_b4d():
    global _struct_b4d
    if _struct_b4d is None:
        _struct_b4d = struct.Struct("<b4d")
    return _struct_b4d
