// Generated by gencpp from file dji_osdk_ros/iuslEstimateState.msg
// DO NOT EDIT!


#ifndef DJI_OSDK_ROS_MESSAGE_IUSLESTIMATESTATE_H
#define DJI_OSDK_ROS_MESSAGE_IUSLESTIMATESTATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dji_osdk_ros
{
template <class ContainerAllocator>
struct iuslEstimateState_
{
  typedef iuslEstimateState_<ContainerAllocator> Type;

  iuslEstimateState_()
    : est_ekf_OK(false)
    , est_tar_x(0.0)
    , est_tar_y(0.0)
    , est_tar_z(0.0)
    , est_tar_vx(0.0)
    , est_tar_vy(0.0)  {
    }
  iuslEstimateState_(const ContainerAllocator& _alloc)
    : est_ekf_OK(false)
    , est_tar_x(0.0)
    , est_tar_y(0.0)
    , est_tar_z(0.0)
    , est_tar_vx(0.0)
    , est_tar_vy(0.0)  {
  (void)_alloc;
    }



   typedef uint8_t _est_ekf_OK_type;
  _est_ekf_OK_type est_ekf_OK;

   typedef double _est_tar_x_type;
  _est_tar_x_type est_tar_x;

   typedef double _est_tar_y_type;
  _est_tar_y_type est_tar_y;

   typedef double _est_tar_z_type;
  _est_tar_z_type est_tar_z;

   typedef double _est_tar_vx_type;
  _est_tar_vx_type est_tar_vx;

   typedef double _est_tar_vy_type;
  _est_tar_vy_type est_tar_vy;





  typedef boost::shared_ptr< ::dji_osdk_ros::iuslEstimateState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dji_osdk_ros::iuslEstimateState_<ContainerAllocator> const> ConstPtr;

}; // struct iuslEstimateState_

typedef ::dji_osdk_ros::iuslEstimateState_<std::allocator<void> > iuslEstimateState;

typedef boost::shared_ptr< ::dji_osdk_ros::iuslEstimateState > iuslEstimateStatePtr;
typedef boost::shared_ptr< ::dji_osdk_ros::iuslEstimateState const> iuslEstimateStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dji_osdk_ros::iuslEstimateState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dji_osdk_ros::iuslEstimateState_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace dji_osdk_ros

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'dji_osdk_ros': ['/home/dji/ningzian_ws/src/Onboard-SDK-ROS/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::dji_osdk_ros::iuslEstimateState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dji_osdk_ros::iuslEstimateState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dji_osdk_ros::iuslEstimateState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dji_osdk_ros::iuslEstimateState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dji_osdk_ros::iuslEstimateState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dji_osdk_ros::iuslEstimateState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dji_osdk_ros::iuslEstimateState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "57b0b6b128ef5651ce9b3fe0084e19a4";
  }

  static const char* value(const ::dji_osdk_ros::iuslEstimateState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x57b0b6b128ef5651ULL;
  static const uint64_t static_value2 = 0xce9b3fe0084e19a4ULL;
};

template<class ContainerAllocator>
struct DataType< ::dji_osdk_ros::iuslEstimateState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dji_osdk_ros/iuslEstimateState";
  }

  static const char* value(const ::dji_osdk_ros::iuslEstimateState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dji_osdk_ros::iuslEstimateState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# estimated target UAV state\n\
bool est_ekf_OK\n\
float64 est_tar_x\n\
float64 est_tar_y\n\
float64 est_tar_z\n\
float64 est_tar_vx\n\
float64 est_tar_vy\n\
\n\
";
  }

  static const char* value(const ::dji_osdk_ros::iuslEstimateState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dji_osdk_ros::iuslEstimateState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.est_ekf_OK);
      stream.next(m.est_tar_x);
      stream.next(m.est_tar_y);
      stream.next(m.est_tar_z);
      stream.next(m.est_tar_vx);
      stream.next(m.est_tar_vy);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct iuslEstimateState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dji_osdk_ros::iuslEstimateState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dji_osdk_ros::iuslEstimateState_<ContainerAllocator>& v)
  {
    s << indent << "est_ekf_OK: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.est_ekf_OK);
    s << indent << "est_tar_x: ";
    Printer<double>::stream(s, indent + "  ", v.est_tar_x);
    s << indent << "est_tar_y: ";
    Printer<double>::stream(s, indent + "  ", v.est_tar_y);
    s << indent << "est_tar_z: ";
    Printer<double>::stream(s, indent + "  ", v.est_tar_z);
    s << indent << "est_tar_vx: ";
    Printer<double>::stream(s, indent + "  ", v.est_tar_vx);
    s << indent << "est_tar_vy: ";
    Printer<double>::stream(s, indent + "  ", v.est_tar_vy);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DJI_OSDK_ROS_MESSAGE_IUSLESTIMATESTATE_H
