// Generated by gencpp from file dji_osdk_ros/iuslGimbalCmd.msg
// DO NOT EDIT!


#ifndef DJI_OSDK_ROS_MESSAGE_IUSLGIMBALCMD_H
#define DJI_OSDK_ROS_MESSAGE_IUSLGIMBALCMD_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dji_osdk_ros
{
template <class ContainerAllocator>
struct iuslGimbalCmd_
{
  typedef iuslGimbalCmd_<ContainerAllocator> Type;

  iuslGimbalCmd_()
    : mode(0)
    , pitch(0.0)
    , roll(0.0)
    , yaw(0.0)
    , time(0.0)  {
    }
  iuslGimbalCmd_(const ContainerAllocator& _alloc)
    : mode(0)
    , pitch(0.0)
    , roll(0.0)
    , yaw(0.0)
    , time(0.0)  {
  (void)_alloc;
    }



   typedef int8_t _mode_type;
  _mode_type mode;

   typedef double _pitch_type;
  _pitch_type pitch;

   typedef double _roll_type;
  _roll_type roll;

   typedef double _yaw_type;
  _yaw_type yaw;

   typedef double _time_type;
  _time_type time;





  typedef boost::shared_ptr< ::dji_osdk_ros::iuslGimbalCmd_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dji_osdk_ros::iuslGimbalCmd_<ContainerAllocator> const> ConstPtr;

}; // struct iuslGimbalCmd_

typedef ::dji_osdk_ros::iuslGimbalCmd_<std::allocator<void> > iuslGimbalCmd;

typedef boost::shared_ptr< ::dji_osdk_ros::iuslGimbalCmd > iuslGimbalCmdPtr;
typedef boost::shared_ptr< ::dji_osdk_ros::iuslGimbalCmd const> iuslGimbalCmdConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dji_osdk_ros::iuslGimbalCmd_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dji_osdk_ros::iuslGimbalCmd_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace dji_osdk_ros

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'dji_osdk_ros': ['/home/dji/ningzian_ws/src/Onboard-SDK-ROS/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::dji_osdk_ros::iuslGimbalCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dji_osdk_ros::iuslGimbalCmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dji_osdk_ros::iuslGimbalCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dji_osdk_ros::iuslGimbalCmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dji_osdk_ros::iuslGimbalCmd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dji_osdk_ros::iuslGimbalCmd_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dji_osdk_ros::iuslGimbalCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "60c32efa40c7049d37a43f7259ece1c9";
  }

  static const char* value(const ::dji_osdk_ros::iuslGimbalCmd_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x60c32efa40c7049dULL;
  static const uint64_t static_value2 = 0x37a43f7259ece1c9ULL;
};

template<class ContainerAllocator>
struct DataType< ::dji_osdk_ros::iuslGimbalCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dji_osdk_ros/iuslGimbalCmd";
  }

  static const char* value(const ::dji_osdk_ros::iuslGimbalCmd_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dji_osdk_ros::iuslGimbalCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 mode    # 0,global fram;   1,local fram\n\
float64 pitch\n\
float64 roll\n\
float64 yaw\n\
float64 time  # seconds\n\
";
  }

  static const char* value(const ::dji_osdk_ros::iuslGimbalCmd_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dji_osdk_ros::iuslGimbalCmd_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mode);
      stream.next(m.pitch);
      stream.next(m.roll);
      stream.next(m.yaw);
      stream.next(m.time);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct iuslGimbalCmd_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dji_osdk_ros::iuslGimbalCmd_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dji_osdk_ros::iuslGimbalCmd_<ContainerAllocator>& v)
  {
    s << indent << "mode: ";
    Printer<int8_t>::stream(s, indent + "  ", v.mode);
    s << indent << "pitch: ";
    Printer<double>::stream(s, indent + "  ", v.pitch);
    s << indent << "roll: ";
    Printer<double>::stream(s, indent + "  ", v.roll);
    s << indent << "yaw: ";
    Printer<double>::stream(s, indent + "  ", v.yaw);
    s << indent << "time: ";
    Printer<double>::stream(s, indent + "  ", v.time);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DJI_OSDK_ROS_MESSAGE_IUSLGIMBALCMD_H
