// Generated by gencpp from file dji_osdk_ros/iuslSetRtkEnable.msg
// DO NOT EDIT!


#ifndef DJI_OSDK_ROS_MESSAGE_IUSLSETRTKENABLE_H
#define DJI_OSDK_ROS_MESSAGE_IUSLSETRTKENABLE_H

#include <ros/service_traits.h>


#include <dji_osdk_ros/iuslSetRtkEnableRequest.h>
#include <dji_osdk_ros/iuslSetRtkEnableResponse.h>


namespace dji_osdk_ros
{

struct iuslSetRtkEnable
{

typedef iuslSetRtkEnableRequest Request;
typedef iuslSetRtkEnableResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct iuslSetRtkEnable
} // namespace dji_osdk_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dji_osdk_ros::iuslSetRtkEnable > {
  static const char* value()
  {
    return "eb13ac1f1354ccecb7941ee8fa2192e8";
  }

  static const char* value(const ::dji_osdk_ros::iuslSetRtkEnable&) { return value(); }
};

template<>
struct DataType< ::dji_osdk_ros::iuslSetRtkEnable > {
  static const char* value()
  {
    return "dji_osdk_ros/iuslSetRtkEnable";
  }

  static const char* value(const ::dji_osdk_ros::iuslSetRtkEnable&) { return value(); }
};


// service_traits::MD5Sum< ::dji_osdk_ros::iuslSetRtkEnableRequest> should match 
// service_traits::MD5Sum< ::dji_osdk_ros::iuslSetRtkEnable > 
template<>
struct MD5Sum< ::dji_osdk_ros::iuslSetRtkEnableRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dji_osdk_ros::iuslSetRtkEnable >::value();
  }
  static const char* value(const ::dji_osdk_ros::iuslSetRtkEnableRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dji_osdk_ros::iuslSetRtkEnableRequest> should match 
// service_traits::DataType< ::dji_osdk_ros::iuslSetRtkEnable > 
template<>
struct DataType< ::dji_osdk_ros::iuslSetRtkEnableRequest>
{
  static const char* value()
  {
    return DataType< ::dji_osdk_ros::iuslSetRtkEnable >::value();
  }
  static const char* value(const ::dji_osdk_ros::iuslSetRtkEnableRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dji_osdk_ros::iuslSetRtkEnableResponse> should match 
// service_traits::MD5Sum< ::dji_osdk_ros::iuslSetRtkEnable > 
template<>
struct MD5Sum< ::dji_osdk_ros::iuslSetRtkEnableResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dji_osdk_ros::iuslSetRtkEnable >::value();
  }
  static const char* value(const ::dji_osdk_ros::iuslSetRtkEnableResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dji_osdk_ros::iuslSetRtkEnableResponse> should match 
// service_traits::DataType< ::dji_osdk_ros::iuslSetRtkEnable > 
template<>
struct DataType< ::dji_osdk_ros::iuslSetRtkEnableResponse>
{
  static const char* value()
  {
    return DataType< ::dji_osdk_ros::iuslSetRtkEnable >::value();
  }
  static const char* value(const ::dji_osdk_ros::iuslSetRtkEnableResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DJI_OSDK_ROS_MESSAGE_IUSLSETRTKENABLE_H
