// Generated by gencpp from file dji_osdk_ros/MFIORequest.msg
// DO NOT EDIT!


#ifndef DJI_OSDK_ROS_MESSAGE_MFIOREQUEST_H
#define DJI_OSDK_ROS_MESSAGE_MFIOREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dji_osdk_ros
{
template <class ContainerAllocator>
struct MFIORequest_
{
  typedef MFIORequest_<ContainerAllocator> Type;

  MFIORequest_()
    : action(0)
    , mode(0)
    , block(false)
    , channel(0)
    , init_on_time_us(0)
    , gpio_value(0)
    , pwm_freq(0)  {
    }
  MFIORequest_(const ContainerAllocator& _alloc)
    : action(0)
    , mode(0)
    , block(false)
    , channel(0)
    , init_on_time_us(0)
    , gpio_value(0)
    , pwm_freq(0)  {
  (void)_alloc;
    }



   typedef uint8_t _action_type;
  _action_type action;

   typedef uint8_t _mode_type;
  _mode_type mode;

   typedef uint8_t _block_type;
  _block_type block;

   typedef uint8_t _channel_type;
  _channel_type channel;

   typedef uint32_t _init_on_time_us_type;
  _init_on_time_us_type init_on_time_us;

   typedef uint8_t _gpio_value_type;
  _gpio_value_type gpio_value;

   typedef uint16_t _pwm_freq_type;
  _pwm_freq_type pwm_freq;



  enum {
    MODE_PWM_OUT = 0u,
    MODE_GPIO_OUT = 2u,
    MODE_GPIO_IN = 3u,
    MODE_ADC = 4u,
    CHANNEL_0 = 0u,
    CHANNEL_1 = 1u,
    CHANNEL_2 = 2u,
    CHANNEL_3 = 3u,
    CHANNEL_4 = 4u,
    CHANNEL_5 = 5u,
    CHANNEL_6 = 6u,
    CHANNEL_7 = 7u,
    TURN_ON = 0u,
    TURN_OFF = 1u,
  };


  typedef boost::shared_ptr< ::dji_osdk_ros::MFIORequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dji_osdk_ros::MFIORequest_<ContainerAllocator> const> ConstPtr;

}; // struct MFIORequest_

typedef ::dji_osdk_ros::MFIORequest_<std::allocator<void> > MFIORequest;

typedef boost::shared_ptr< ::dji_osdk_ros::MFIORequest > MFIORequestPtr;
typedef boost::shared_ptr< ::dji_osdk_ros::MFIORequest const> MFIORequestConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   

   

   

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dji_osdk_ros::MFIORequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dji_osdk_ros::MFIORequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace dji_osdk_ros

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'dji_osdk_ros': ['/home/dji/ningzian_ws/src/Onboard-SDK-ROS/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::dji_osdk_ros::MFIORequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dji_osdk_ros::MFIORequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dji_osdk_ros::MFIORequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dji_osdk_ros::MFIORequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dji_osdk_ros::MFIORequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dji_osdk_ros::MFIORequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dji_osdk_ros::MFIORequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5a9f232a9ad94c1663aa32b8a91f6ba6";
  }

  static const char* value(const ::dji_osdk_ros::MFIORequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5a9f232a9ad94c16ULL;
  static const uint64_t static_value2 = 0x63aa32b8a91f6ba6ULL;
};

template<class ContainerAllocator>
struct DataType< ::dji_osdk_ros::MFIORequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dji_osdk_ros/MFIORequest";
  }

  static const char* value(const ::dji_osdk_ros::MFIORequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dji_osdk_ros::MFIORequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
uint8 MODE_PWM_OUT  = 0\n\
\n\
uint8 MODE_GPIO_OUT = 2\n\
uint8 MODE_GPIO_IN  = 3\n\
uint8 MODE_ADC      = 4\n\
\n\
uint8 CHANNEL_0 = 0\n\
uint8 CHANNEL_1 = 1\n\
uint8 CHANNEL_2 = 2\n\
uint8 CHANNEL_3 = 3\n\
uint8 CHANNEL_4 = 4\n\
uint8 CHANNEL_5 = 5\n\
uint8 CHANNEL_6 = 6\n\
uint8 CHANNEL_7 = 7\n\
\n\
uint8 TURN_ON   = 0\n\
uint8 TURN_OFF  = 1\n\
\n\
\n\
uint8 action\n\
uint8 mode\n\
bool block\n\
uint8 channel\n\
uint32 init_on_time_us\n\
uint8 gpio_value\n\
uint16 pwm_freq\n\
";
  }

  static const char* value(const ::dji_osdk_ros::MFIORequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dji_osdk_ros::MFIORequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.action);
      stream.next(m.mode);
      stream.next(m.block);
      stream.next(m.channel);
      stream.next(m.init_on_time_us);
      stream.next(m.gpio_value);
      stream.next(m.pwm_freq);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MFIORequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dji_osdk_ros::MFIORequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dji_osdk_ros::MFIORequest_<ContainerAllocator>& v)
  {
    s << indent << "action: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.action);
    s << indent << "mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mode);
    s << indent << "block: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.block);
    s << indent << "channel: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.channel);
    s << indent << "init_on_time_us: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.init_on_time_us);
    s << indent << "gpio_value: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.gpio_value);
    s << indent << "pwm_freq: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.pwm_freq);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DJI_OSDK_ROS_MESSAGE_MFIOREQUEST_H
