// Generated by gencpp from file dji_osdk_ros/SetupCameraH264Request.msg
// DO NOT EDIT!


#ifndef DJI_OSDK_ROS_MESSAGE_SETUPCAMERAH264REQUEST_H
#define DJI_OSDK_ROS_MESSAGE_SETUPCAMERAH264REQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dji_osdk_ros
{
template <class ContainerAllocator>
struct SetupCameraH264Request_
{
  typedef SetupCameraH264Request_<ContainerAllocator> Type;

  SetupCameraH264Request_()
    : request_view(0)
    , start(0)  {
    }
  SetupCameraH264Request_(const ContainerAllocator& _alloc)
    : request_view(0)
    , start(0)  {
  (void)_alloc;
    }



   typedef uint8_t _request_view_type;
  _request_view_type request_view;

   typedef uint8_t _start_type;
  _start_type start;



  enum {
    FPV_CAMERA = 7u,
    MAIN_CAMERA = 0u,
    VICE_CAMERA = 1u,
    TOP_CAMERA = 2u,
  };


  typedef boost::shared_ptr< ::dji_osdk_ros::SetupCameraH264Request_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dji_osdk_ros::SetupCameraH264Request_<ContainerAllocator> const> ConstPtr;

}; // struct SetupCameraH264Request_

typedef ::dji_osdk_ros::SetupCameraH264Request_<std::allocator<void> > SetupCameraH264Request;

typedef boost::shared_ptr< ::dji_osdk_ros::SetupCameraH264Request > SetupCameraH264RequestPtr;
typedef boost::shared_ptr< ::dji_osdk_ros::SetupCameraH264Request const> SetupCameraH264RequestConstPtr;

// constants requiring out of line definition

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dji_osdk_ros::SetupCameraH264Request_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dji_osdk_ros::SetupCameraH264Request_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace dji_osdk_ros

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'dji_osdk_ros': ['/home/dji/ningzian_ws/src/Onboard-SDK-ROS/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::dji_osdk_ros::SetupCameraH264Request_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dji_osdk_ros::SetupCameraH264Request_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dji_osdk_ros::SetupCameraH264Request_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dji_osdk_ros::SetupCameraH264Request_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dji_osdk_ros::SetupCameraH264Request_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dji_osdk_ros::SetupCameraH264Request_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dji_osdk_ros::SetupCameraH264Request_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bbc9edd450365b3e5b6c4e71c439e0d4";
  }

  static const char* value(const ::dji_osdk_ros::SetupCameraH264Request_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbbc9edd450365b3eULL;
  static const uint64_t static_value2 = 0x5b6c4e71c439e0d4ULL;
};

template<class ContainerAllocator>
struct DataType< ::dji_osdk_ros::SetupCameraH264Request_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dji_osdk_ros/SetupCameraH264Request";
  }

  static const char* value(const ::dji_osdk_ros::SetupCameraH264Request_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dji_osdk_ros::SetupCameraH264Request_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
uint8 FPV_CAMERA  = 7\n\
uint8 MAIN_CAMERA = 0\n\
uint8 VICE_CAMERA = 1\n\
uint8 TOP_CAMERA  = 2\n\
\n\
\n\
uint8 request_view\n\
\n\
\n\
uint8 start\n\
\n\
";
  }

  static const char* value(const ::dji_osdk_ros::SetupCameraH264Request_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dji_osdk_ros::SetupCameraH264Request_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.request_view);
      stream.next(m.start);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetupCameraH264Request_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dji_osdk_ros::SetupCameraH264Request_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dji_osdk_ros::SetupCameraH264Request_<ContainerAllocator>& v)
  {
    s << indent << "request_view: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.request_view);
    s << indent << "start: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.start);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DJI_OSDK_ROS_MESSAGE_SETUPCAMERAH264REQUEST_H
