// Generated by gencpp from file dji_osdk_ros/VOPosition.msg
// DO NOT EDIT!


#ifndef DJI_OSDK_ROS_MESSAGE_VOPOSITION_H
#define DJI_OSDK_ROS_MESSAGE_VOPOSITION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace dji_osdk_ros
{
template <class ContainerAllocator>
struct VOPosition_
{
  typedef VOPosition_<ContainerAllocator> Type;

  VOPosition_()
    : header()
    , x(0.0)
    , y(0.0)
    , z(0.0)
    , xHealth(0)
    , yHealth(0)
    , zHealth(0)  {
    }
  VOPosition_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , x(0.0)
    , y(0.0)
    , z(0.0)
    , xHealth(0)
    , yHealth(0)
    , zHealth(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _z_type;
  _z_type z;

   typedef uint8_t _xHealth_type;
  _xHealth_type xHealth;

   typedef uint8_t _yHealth_type;
  _yHealth_type yHealth;

   typedef uint8_t _zHealth_type;
  _zHealth_type zHealth;





  typedef boost::shared_ptr< ::dji_osdk_ros::VOPosition_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dji_osdk_ros::VOPosition_<ContainerAllocator> const> ConstPtr;

}; // struct VOPosition_

typedef ::dji_osdk_ros::VOPosition_<std::allocator<void> > VOPosition;

typedef boost::shared_ptr< ::dji_osdk_ros::VOPosition > VOPositionPtr;
typedef boost::shared_ptr< ::dji_osdk_ros::VOPosition const> VOPositionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dji_osdk_ros::VOPosition_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dji_osdk_ros::VOPosition_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace dji_osdk_ros

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'dji_osdk_ros': ['/home/dji/ningzian_ws/src/Onboard-SDK-ROS/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::dji_osdk_ros::VOPosition_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dji_osdk_ros::VOPosition_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dji_osdk_ros::VOPosition_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dji_osdk_ros::VOPosition_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dji_osdk_ros::VOPosition_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dji_osdk_ros::VOPosition_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dji_osdk_ros::VOPosition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6edcbd5875a94886d3601c7c54dba55d";
  }

  static const char* value(const ::dji_osdk_ros::VOPosition_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6edcbd5875a94886ULL;
  static const uint64_t static_value2 = 0xd3601c7c54dba55dULL;
};

template<class ContainerAllocator>
struct DataType< ::dji_osdk_ros::VOPosition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dji_osdk_ros/VOPosition";
  }

  static const char* value(const ::dji_osdk_ros::VOPosition_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dji_osdk_ros::VOPosition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
float32 x\n\
float32 y\n\
float32 z\n\
uint8   xHealth\n\
uint8   yHealth\n\
uint8   zHealth\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::dji_osdk_ros::VOPosition_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dji_osdk_ros::VOPosition_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.xHealth);
      stream.next(m.yHealth);
      stream.next(m.zHealth);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VOPosition_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dji_osdk_ros::VOPosition_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dji_osdk_ros::VOPosition_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<float>::stream(s, indent + "  ", v.z);
    s << indent << "xHealth: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.xHealth);
    s << indent << "yHealth: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.yHealth);
    s << indent << "zHealth: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.zHealth);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DJI_OSDK_ROS_MESSAGE_VOPOSITION_H
