// Generated by gencpp from file dji_osdk_ros/WaypointV2ReachpointTrigger.msg
// DO NOT EDIT!


#ifndef DJI_OSDK_ROS_MESSAGE_WAYPOINTV2REACHPOINTTRIGGER_H
#define DJI_OSDK_ROS_MESSAGE_WAYPOINTV2REACHPOINTTRIGGER_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dji_osdk_ros
{
template <class ContainerAllocator>
struct WaypointV2ReachpointTrigger_
{
  typedef WaypointV2ReachpointTrigger_<ContainerAllocator> Type;

  WaypointV2ReachpointTrigger_()
    : startIndex(0)
    , endIndex(0)
    , intervalWPNum(0)
    , waypointCountToTerminate(0)  {
    }
  WaypointV2ReachpointTrigger_(const ContainerAllocator& _alloc)
    : startIndex(0)
    , endIndex(0)
    , intervalWPNum(0)
    , waypointCountToTerminate(0)  {
  (void)_alloc;
    }



   typedef uint16_t _startIndex_type;
  _startIndex_type startIndex;

   typedef uint16_t _endIndex_type;
  _endIndex_type endIndex;

   typedef uint16_t _intervalWPNum_type;
  _intervalWPNum_type intervalWPNum;

   typedef uint16_t _waypointCountToTerminate_type;
  _waypointCountToTerminate_type waypointCountToTerminate;





  typedef boost::shared_ptr< ::dji_osdk_ros::WaypointV2ReachpointTrigger_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dji_osdk_ros::WaypointV2ReachpointTrigger_<ContainerAllocator> const> ConstPtr;

}; // struct WaypointV2ReachpointTrigger_

typedef ::dji_osdk_ros::WaypointV2ReachpointTrigger_<std::allocator<void> > WaypointV2ReachpointTrigger;

typedef boost::shared_ptr< ::dji_osdk_ros::WaypointV2ReachpointTrigger > WaypointV2ReachpointTriggerPtr;
typedef boost::shared_ptr< ::dji_osdk_ros::WaypointV2ReachpointTrigger const> WaypointV2ReachpointTriggerConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dji_osdk_ros::WaypointV2ReachpointTrigger_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dji_osdk_ros::WaypointV2ReachpointTrigger_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace dji_osdk_ros

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'dji_osdk_ros': ['/home/dji/ningzian_ws/src/Onboard-SDK-ROS/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::dji_osdk_ros::WaypointV2ReachpointTrigger_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dji_osdk_ros::WaypointV2ReachpointTrigger_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dji_osdk_ros::WaypointV2ReachpointTrigger_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dji_osdk_ros::WaypointV2ReachpointTrigger_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dji_osdk_ros::WaypointV2ReachpointTrigger_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dji_osdk_ros::WaypointV2ReachpointTrigger_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dji_osdk_ros::WaypointV2ReachpointTrigger_<ContainerAllocator> >
{
  static const char* value()
  {
    return "97fe6c65510583177587ba40623a3408";
  }

  static const char* value(const ::dji_osdk_ros::WaypointV2ReachpointTrigger_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x97fe6c6551058317ULL;
  static const uint64_t static_value2 = 0x7587ba40623a3408ULL;
};

template<class ContainerAllocator>
struct DataType< ::dji_osdk_ros::WaypointV2ReachpointTrigger_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dji_osdk_ros/WaypointV2ReachpointTrigger";
  }

  static const char* value(const ::dji_osdk_ros::WaypointV2ReachpointTrigger_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dji_osdk_ros::WaypointV2ReachpointTrigger_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#  It describes an action will be triggered when the aircraft reach the certain waypoint.\n\
  uint16 startIndex   # It determines the index of the waypoint at which the action will be triggered.\n\
  uint16 endIndex\n\
  uint16 intervalWPNum\n\
  uint16 waypointCountToTerminate  # It determines the waypoint count till the action triggered stops.\n\
";
  }

  static const char* value(const ::dji_osdk_ros::WaypointV2ReachpointTrigger_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dji_osdk_ros::WaypointV2ReachpointTrigger_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.startIndex);
      stream.next(m.endIndex);
      stream.next(m.intervalWPNum);
      stream.next(m.waypointCountToTerminate);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WaypointV2ReachpointTrigger_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dji_osdk_ros::WaypointV2ReachpointTrigger_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dji_osdk_ros::WaypointV2ReachpointTrigger_<ContainerAllocator>& v)
  {
    s << indent << "startIndex: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.startIndex);
    s << indent << "endIndex: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.endIndex);
    s << indent << "intervalWPNum: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.intervalWPNum);
    s << indent << "waypointCountToTerminate: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.waypointCountToTerminate);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DJI_OSDK_ROS_MESSAGE_WAYPOINTV2REACHPOINTTRIGGER_H
