(cl:in-package dji_osdk_ros-msg)
(cl:export '(TIME-VAL
          TIME
          CENTER_X-VAL
          CENTER_X
          CENTER_Y-VAL
          CENTER_Y
          BOX_WIDTH-VAL
          BOX_WIDTH
          BOX_HEIGHT-VAL
          BOX_HEIGHT
          MAX_LENGTH-VAL
          MAX_LENGTH
          UAV_LAT-VAL
          UAV_LAT
          UAV_LON-VAL
          UAV_LON
          UAV_ALT-VAL
          UAV_ALT
          UAV_ROLL-VAL
          UAV_ROLL
          UAV_PITCH-VAL
          UAV_PITCH
          UAV_YAW-VAL
          UAV_YAW
          CAM_ROLL-VAL
          CAM_ROLL
          CAM_PITCH-VAL
          CAM_PITCH
          CAM_YAW-VAL
          CAM_YAW
          LASER_DIS-VAL
          LASER_DIS
))